---
title: "Gov 50 Final Project"
author: "Aaryan Rawal"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does more citizen engagement lead in public comment portions lead to bill advancement? I plan to analyze the effect of  comments made impact a bill's advancement in state legislatures. I will be using the "Replication Data for: Does Lobbying Affect Bill Advancement? Evidence from Three State Legislatures." I hypothesize that increased public comments made in support of a bill lead to increased chances of advancement for bills introduced by the majority party, but have a minimally positive change on the advancement of bills introduced by the minority party. This is because for bills from members of the majority party that have large engagement, it likely indicates that the bill speaks to an issue area that is a priority for the political party. In contrast, bills from that minority party with large public engagement may not overcome the partisan disadvantages of state legislatures. I'm particularly interested in the impact of public comments on a bill introduced by a minority party compared to a bill introduced by the majority party with no enagegment. Such a comparison can potentially reveal whether public comments can overcome partisan disadvantages. The explanatory variable is the amount of pyblic comments made for a bill and against a bill. This can reflect lobbying for and against a bill. The outcome variable is how far the bill advances in the state legislator.  If a bill introduced by the majority party with a significant number of public comments in favor advanced in the state legislature, this would support my hypothesis. Likewise, if a bill introduced by a minority party with a significant number of public comments in favor, and it does not advance in the state legislature, it would support my hypoethesis. 


